# Generated by Django 4.2.30 on 2026-09-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Duyuru Başlığı')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Kısa Özet')),
                ('content', models.TextField(verbose_name='Detaylı İçerik')),
                ('category', models.CharField(choices=[('asm', 'Binkılıç ASM Duyurusu'), ('ministry', 'T.C. Sağlık Bakanlığı Haberi'), ('campaign', 'Aşı / Tarama Kampanyası')], default='asm', max_length=50, verbose_name='Kategori')),
                ('image_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Görsel Yolu')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Dış Haber Bağlantısı')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkarılsın mı?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Duyuru ve Haber',
                'verbose_name_plural': 'Duyurular ve Haberler',
                'ordering': ['-published_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ASMInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Binkılıç Aile Sağlığı Merkezi', max_length=255, verbose_name='ASM Adı')),
                ('district', models.CharField(default='Çatalca', max_length=100, verbose_name='İlçe')),
                ('city', models.CharField(default='İstanbul', max_length=100, verbose_name='İl')),
                ('phone', models.CharField(default='0212 789 6334', max_length=50, verbose_name='Sabit Telefon')),
                ('whatsapp', models.CharField(default='05461286629', max_length=50, verbose_name='WhatsApp Hattı')),
                ('email', models.EmailField(default='binkilicasm@gmail.com', max_length=254, verbose_name='E-Posta')),
                ('address', models.TextField(default='Atatürk Mah. İstanbul Cad. No: 2 Semih Sokak Binkılıç, Çatalca / İstanbul', verbose_name='Açık Adres')),
                ('building_image', models.ImageField(blank=True, null=True, upload_to='asm/', verbose_name='ASM Binası Görseli')),
                ('map_lat', models.FloatField(default=41.4107, verbose_name='Enlem (Lat)')),
                ('map_lng', models.FloatField(default=28.1846, verbose_name='Boylam (Lng)')),
                ('working_hours', models.CharField(default='Hafta içi 08:00 - 17:00 (Esnek Mesai 08:00 - 19:00)', max_length=255, verbose_name='Çalışma Saatleri')),
                ('lab_hours', models.CharField(default='Hafta içi 08:30 - 10:30', max_length=255, verbose_name='Kan Alma Saatleri')),
                ('about_text', models.TextField(blank=True, default='', verbose_name='Hakkımızda Metni')),
            ],
            options={
                'verbose_name': 'ASM Genel Bilgisi',
                'verbose_name_plural': 'ASM Genel Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Hekim Adı Soyadı')),
                ('title', models.CharField(default='Aile Hekimi', max_length=100, verbose_name='Unvan')),
                ('unit_no', models.CharField(max_length=50, verbose_name='Aile Hekimliği Birim No')),
                ('room_no', models.CharField(default='1', max_length=50, verbose_name='Poliklinik Oda No')),
                ('mobile_villages', models.CharField(blank=True, default='', max_length=255, verbose_name='Gezici Sağlık Köyleri')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Özgeçmiş / Açıklama')),
                ('schedule', models.TextField(blank=True, default='', verbose_name='Mesai & Gezici Hizmet Programı')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('avatar_color', models.CharField(default='#0284c7', max_length=50, verbose_name='Avatar Tema Rengi')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Aile Hekimi',
                'verbose_name_plural': 'Aile Hekimlerimiz',
                'ordering': ['order', 'unit_no'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dosya Başlığı')),
                ('category', models.CharField(choices=[('talimatlar', 'ASM Talimatları'), ('ilk_yardim', 'İlk Yardım Kılavuzları'), ('sigara', 'Sigaranın Zararları & Bırakma'), ('faydali', 'Faydalı Dosyalar ve Formlar')], default='faydali', max_length=50, verbose_name='Kategori')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('file_path', models.CharField(max_length=255, verbose_name='Dosya Yolu (PDF / Doküman)')),
                ('file_size', models.CharField(default='PDF', max_length=50, verbose_name='Dosya Türü / Boyutu')),
            ],
            options={
                'verbose_name': 'İndirilebilir Doküman',
                'verbose_name_plural': 'İndirilebilir Dokümanlar',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Görsel Başlığı')),
                ('category', models.CharField(default='Merkezimiz', max_length=50, verbose_name='Kategori')),
                ('image_url', models.CharField(max_length=255, verbose_name='Görsel Yolu')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Foto Galeri Ögesi',
                'verbose_name_plural': 'Foto Galeri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HealthGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Rehber Başlığı')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('asm_guide', 'ASM Rehberi'), ('health_info', 'Sağlık Bilgilendirme'), ('pregnancy', 'Gebelik Dönemi'), ('newborn', 'Yenidoğan Rehberi')], default='asm_guide', max_length=50, verbose_name='Kategori')),
                ('summary', models.TextField(verbose_name='Özet Bilgi')),
                ('content', models.TextField(verbose_name='Tam Makale / Kılavuz Metni')),
                ('icon', models.CharField(default='BookOpen', max_length=50, verbose_name='İkon')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sağlık / ASM Rehberi',
                'verbose_name_plural': 'Sağlık ve ASM Rehberleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MobileHealthService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100, verbose_name='Köy / Mahalle Adı')),
                ('doctor_name', models.CharField(max_length=150, verbose_name='Sorumlu Aile Hekimi')),
                ('days_and_hours', models.CharField(max_length=200, verbose_name='Ziyaret Gün ve Saatleri')),
                ('service_location', models.CharField(max_length=200, verbose_name='Hizmet Verilen Yer (örn. Köy Sağlık Evi)')),
                ('services', models.TextField(verbose_name='Verilen Sağlık Hizmetleri (Muayene, Aşı, Reçete, Kan Alımı)')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gezici Sağlık Hizmeti',
                'verbose_name_plural': 'Gezici Sağlık Hizmetleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('gebe', 'Gebe Bildirimi'), ('bebek', 'Bebek / Çocuk Bildirimi'), ('engelli', 'Engelli Hasta Bildirimi'), ('obezite', 'Obezite İzlem Bildirimi'), ('soru', 'Doktora Soru / Danışma'), ('genel', 'Genel İletişim / İstek / Şikayet')], default='genel', max_length=50, verbose_name='Bildirim Türü')),
                ('full_name', models.CharField(max_length=150, verbose_name='Adı Soyadı')),
                ('tc_no', models.CharField(blank=True, default='', max_length=11, verbose_name='T.C. Kimlik No')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Posta Adresi')),
                ('target_doctor', models.CharField(blank=True, default='Fark Etmez', max_length=150, verbose_name='İlgili Hekim')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj / Bildirim Detayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='İncelendi mi?')),
            ],
            options={
                'verbose_name': 'Hasta Bildirimi & İletişim Formu',
                'verbose_name_plural': 'Hasta Bildirimleri ve İletişim Formları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Hizmet Adı')),
                ('description', models.TextField(verbose_name='Hizmet Açıklaması')),
                ('icon', models.CharField(default='Activity', max_length=50, verbose_name='İkon Adı')),
                ('standard_duration', models.CharField(default='15 Dakika', max_length=50, verbose_name='Standart Hizmet Süresi')),
                ('category', models.CharField(default='Genel', max_length=100, verbose_name='Kategori')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Sağlık Hizmeti',
                'verbose_name_plural': 'Sağlık Hizmetlerimiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Personel Adı Soyadı')),
                ('title', models.CharField(max_length=100, verbose_name='Unvanı (örn: Hemşire, Ebe, Destek Personeli)')),
                ('role_type', models.CharField(choices=[('nurse', 'Hemşire / Ebe (Aile Sağlığı Çalışanı)'), ('midwife', 'Ebe'), ('support', 'Yardımcı & Destek Personeli'), ('cleaning', 'Temizlik Personeli')], default='nurse', max_length=50, verbose_name='Personel Rolü')),
                ('assigned_doctor', models.CharField(blank=True, default='', max_length=150, verbose_name='Bağlı Olduğu Hekim / Birim')),
                ('duties', models.TextField(blank=True, default='', verbose_name='Görev ve Sorumlulukları')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Aile Sağlığı Çalışanı / Personel',
                'verbose_name_plural': 'Sağlık Çalışanlarımız ve Personel',
                'ordering': ['order', 'name'],
            },
        ),
    ]
