# Generated by Django 4.2.30 on 2026-09-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnotification',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon Numarası (Opsiyonel)'),
        ),
        migrations.AlterField(
            model_name='patientnotification',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='patientnotification',
            name='tc_no',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='T.C. Kimlik No (Opsiyonel)'),
        ),
    ]
